/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\workspace\\vuepress\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-3494935d",
    path: "/api/cli.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3494935d").then(next)
    },
  },
  {
    name: "v-215ebb1e",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-215ebb1e").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-7c20b7bb",
    path: "/api/node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7c20b7bb").then(next)
    },
  },
  {
    name: "v-3d9f9f58",
    path: "/config/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3d9f9f58").then(next)
    },
  },
  {
    path: "/config/index.html",
    redirect: "/config/"
  },
  {
    name: "v-11bd2ad0",
    path: "/faq/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-11bd2ad0").then(next)
    },
  },
  {
    path: "/faq/index.html",
    redirect: "/faq/"
  },
  {
    name: "v-791f5484",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-791f5484").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-24e6397d",
    path: "/guide/assets.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-24e6397d").then(next)
    },
  },
  {
    name: "v-56bf8afe",
    path: "/guide/basic-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-56bf8afe").then(next)
    },
  },
  {
    name: "v-63dfb95d",
    path: "/guide/frontmatter.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-63dfb95d").then(next)
    },
  },
  {
    name: "v-320f8672",
    path: "/guide/i18n.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-320f8672").then(next)
    },
  },
  {
    name: "v-415e03b5",
    path: "/guide/deploy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-415e03b5").then(next)
    },
  },
  {
    name: "v-0ff9ab86",
    path: "/guide/global-computed.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0ff9ab86").then(next)
    },
  },
  {
    name: "v-18b6885d",
    path: "/guide/markdown-slot.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-18b6885d").then(next)
    },
  },
  {
    name: "v-6323f525",
    path: "/guide/markdown.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6323f525").then(next)
    },
  },
  {
    name: "v-2d23e673",
    path: "/guide/permalinks.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d23e673").then(next)
    },
  },
  {
    name: "v-3c940e19",
    path: "/guide/typescript-as-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3c940e19").then(next)
    },
  },
  {
    name: "v-4bc25d7d",
    path: "/guide/using-vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4bc25d7d").then(next)
    },
  },
  {
    name: "v-7b67f11e",
    path: "/guide/%E7%99%BB%E5%BD%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b67f11e").then(next)
    },
  },
  {
    path: "/guide/登录.html",
    redirect: "/guide/%E7%99%BB%E5%BD%95.html"
  },
  {
    path: "/guide/登录.html",
    redirect: "/guide/%E7%99%BB%E5%BD%95.html"
  },
  {
    name: "v-463ad71e",
    path: "/guide/%E8%B7%AF%E7%94%B1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-463ad71e").then(next)
    },
  },
  {
    path: "/guide/路由.html",
    redirect: "/guide/%E8%B7%AF%E7%94%B1.html"
  },
  {
    path: "/guide/路由.html",
    redirect: "/guide/%E8%B7%AF%E7%94%B1.html"
  },
  {
    name: "v-cd0216c6",
    path: "/miscellaneous/design-concepts.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cd0216c6").then(next)
    },
  },
  {
    name: "v-c498c4aa",
    path: "/miscellaneous/glossary.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c498c4aa").then(next)
    },
  },
  {
    name: "v-36439986",
    path: "/miscellaneous/local-development.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-36439986").then(next)
    },
  },
  {
    name: "v-69d0b786",
    path: "/miscellaneous/migration-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-69d0b786").then(next)
    },
  },
  {
    name: "v-58e21798",
    path: "/plugin/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-58e21798").then(next)
    },
  },
  {
    path: "/plugin/index.html",
    redirect: "/plugin/"
  },
  {
    name: "v-37f2f563",
    path: "/plugin/context-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-37f2f563").then(next)
    },
  },
  {
    name: "v-69abe2d7",
    path: "/plugin/life-cycle.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-69abe2d7").then(next)
    },
  },
  {
    name: "v-2619487a",
    path: "/plugin/official/plugin-active-header-links.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2619487a").then(next)
    },
  },
  {
    name: "v-0ae13ee8",
    path: "/plugin/official/plugin-back-to-top.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0ae13ee8").then(next)
    },
  },
  {
    name: "v-14dc6baa",
    path: "/plugin/official/plugin-blog.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-14dc6baa").then(next)
    },
  },
  {
    name: "v-14b3abaa",
    path: "/plugin/official/plugin-google-analytics.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-14b3abaa").then(next)
    },
  },
  {
    name: "v-4e7679e4",
    path: "/plugin/official/plugin-medium-zoom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4e7679e4").then(next)
    },
  },
  {
    name: "v-46c1dc2c",
    path: "/plugin/official/plugin-last-updated.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-46c1dc2c").then(next)
    },
  },
  {
    name: "v-b452fa78",
    path: "/plugin/official/plugin-nprogress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b452fa78").then(next)
    },
  },
  {
    name: "v-4402c074",
    path: "/plugin/official/plugin-pwa.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4402c074").then(next)
    },
  },
  {
    name: "v-250327ea",
    path: "/plugin/official/plugin-search.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-250327ea").then(next)
    },
  },
  {
    name: "v-5410df3a",
    path: "/plugin/official/plugin-register-components.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5410df3a").then(next)
    },
  },
  {
    name: "v-55e54412",
    path: "/plugin/using-a-plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-55e54412").then(next)
    },
  },
  {
    name: "v-5793d0b7",
    path: "/plugin/option-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5793d0b7").then(next)
    },
  },
  {
    name: "v-5c118c2a",
    path: "/theme/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5c118c2a").then(next)
    },
  },
  {
    path: "/theme/index.html",
    redirect: "/theme/"
  },
  {
    name: "v-86672d12",
    path: "/plugin/writing-a-plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-86672d12").then(next)
    },
  },
  {
    name: "v-63256021",
    path: "/theme/blog-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-63256021").then(next)
    },
  },
  {
    name: "v-5128e88e",
    path: "/theme/default-theme-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5128e88e").then(next)
    },
  },
  {
    name: "v-33e6dd59",
    path: "/theme/option-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-33e6dd59").then(next)
    },
  },
  {
    name: "v-379fb186",
    path: "/theme/inheritance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-379fb186").then(next)
    },
  },
  {
    name: "v-b1a24c06",
    path: "/theme/using-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b1a24c06").then(next)
    },
  },
  {
    name: "v-3483a3fd",
    path: "/theme/writing-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3483a3fd").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]